// Generated by: npm run db:types (after every migration). Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      app_settings: {
        Row: {
          key: string
          value: Json
        }
        Insert: {
          key: string
          value: Json
        }
        Update: {
          key?: string
          value?: Json
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          at: string
          details: Json
          entity: string
          entity_id: string
          from_status: Database["public"]["Enums"]["request_status"] | null
          id: number
          to_status: Database["public"]["Enums"]["request_status"] | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          at: string
          details?: Json
          entity: string
          entity_id: string
          from_status?: Database["public"]["Enums"]["request_status"] | null
          id?: never
          to_status?: Database["public"]["Enums"]["request_status"] | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          at?: string
          details?: Json
          entity?: string
          entity_id?: string
          from_status?: Database["public"]["Enums"]["request_status"] | null
          id?: never
          to_status?: Database["public"]["Enums"]["request_status"] | null
        }
        Relationships: []
      }
      buildings: {
        Row: {
          code: string
          id: string
          lat: number | null
          lng: number | null
          name: string
        }
        Insert: {
          code: string
          id?: string
          lat?: number | null
          lng?: number | null
          name: string
        }
        Update: {
          code?: string
          id?: string
          lat?: number | null
          lng?: number | null
          name?: string
        }
        Relationships: []
      }
      demo_tokens: {
        Row: {
          expires_at: string | null
          token: string
          used_count: number
          user_id: string | null
        }
        Insert: {
          expires_at?: string | null
          token: string
          used_count?: number
          user_id?: string | null
        }
        Update: {
          expires_at?: string | null
          token?: string
          used_count?: number
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "demo_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      departments: {
        Row: {
          building_id: string | null
          code: string
          id: string
          name: string
        }
        Insert: {
          building_id?: string | null
          code: string
          id?: string
          name: string
        }
        Update: {
          building_id?: string | null
          code?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "departments_building_id_fkey"
            columns: ["building_id"]
            isOneToOne: false
            referencedRelation: "buildings"
            referencedColumns: ["id"]
          },
        ]
      }
      engine_runs: {
        Row: {
          created_at: string
          id: string
          input: Json | null
          kind: string
          ms: number | null
          output: Json | null
          solver: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          input?: Json | null
          kind: string
          ms?: number | null
          output?: Json | null
          solver?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          input?: Json | null
          kind?: string
          ms?: number | null
          output?: Json | null
          solver?: string | null
        }
        Relationships: []
      }
      lab_scenarios: {
        Row: {
          description: string | null
          id: string
          name: string
          requests: Json
        }
        Insert: {
          description?: string | null
          id: string
          name: string
          requests: Json
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          requests?: Json
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          kind: string
          read_at: string | null
          request_id: string | null
          title: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at: string
          id?: string
          kind: string
          read_at?: string | null
          request_id?: string | null
          title: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: string
          read_at?: string | null
          request_id?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          department_id: string | null
          full_name: string
          id: string
          kind: Database["public"]["Enums"]["requester_kind"] | null
          org_name: string | null
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          department_id?: string | null
          full_name: string
          id: string
          kind?: Database["public"]["Enums"]["requester_kind"] | null
          org_name?: string | null
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          department_id?: string | null
          full_name?: string
          id?: string
          kind?: Database["public"]["Enums"]["requester_kind"] | null
          org_name?: string | null
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: [
          {
            foreignKeyName: "profiles_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
      requests: {
        Row: {
          checked_in_at: string | null
          created_at: string
          decided_by: string | null
          decision_reason: string | null
          during: unknown
          headcount: number
          hold_expires_at: string | null
          id: string
          last_action: string | null
          last_action_at: string | null
          last_actor_id: string | null
          min_systems: number
          offered_alternatives: Json | null
          preferred_building_id: string | null
          priority: number
          purpose: Database["public"]["Enums"]["purpose_kind"]
          raw_input: string | null
          requester_id: string
          required_features: string[]
          room_id: string | null
          room_type: Database["public"]["Enums"]["room_type"] | null
          score_breakdown: Json | null
          source: string
          status: Database["public"]["Enums"]["request_status"]
          title: string
          unplaced_reason: string | null
          updated_at: string
        }
        Insert: {
          checked_in_at?: string | null
          created_at: string
          decided_by?: string | null
          decision_reason?: string | null
          during: unknown
          headcount: number
          hold_expires_at?: string | null
          id?: string
          last_action?: string | null
          last_action_at?: string | null
          last_actor_id?: string | null
          min_systems?: number
          offered_alternatives?: Json | null
          preferred_building_id?: string | null
          priority: number
          purpose: Database["public"]["Enums"]["purpose_kind"]
          raw_input?: string | null
          requester_id: string
          required_features?: string[]
          room_id?: string | null
          room_type?: Database["public"]["Enums"]["room_type"] | null
          score_breakdown?: Json | null
          source?: string
          status?: Database["public"]["Enums"]["request_status"]
          title: string
          unplaced_reason?: string | null
          updated_at?: string
        }
        Update: {
          checked_in_at?: string | null
          created_at?: string
          decided_by?: string | null
          decision_reason?: string | null
          during?: unknown
          headcount?: number
          hold_expires_at?: string | null
          id?: string
          last_action?: string | null
          last_action_at?: string | null
          last_actor_id?: string | null
          min_systems?: number
          offered_alternatives?: Json | null
          preferred_building_id?: string | null
          priority?: number
          purpose?: Database["public"]["Enums"]["purpose_kind"]
          raw_input?: string | null
          requester_id?: string
          required_features?: string[]
          room_id?: string | null
          room_type?: Database["public"]["Enums"]["room_type"] | null
          score_breakdown?: Json | null
          source?: string
          status?: Database["public"]["Enums"]["request_status"]
          title?: string
          unplaced_reason?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "requests_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "requests_last_actor_id_fkey"
            columns: ["last_actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "requests_preferred_building_id_fkey"
            columns: ["preferred_building_id"]
            isOneToOne: false
            referencedRelation: "buildings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "requests_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "requests_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      room_blackouts: {
        Row: {
          created_at: string
          created_by: string | null
          during: unknown
          id: string
          reason: string
          room_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          during: unknown
          id?: string
          reason: string
          room_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          during?: unknown
          id?: string
          reason?: string
          room_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_blackouts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_blackouts_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      rooms: {
        Row: {
          access: Database["public"]["Enums"]["access_rule"]
          approver_id: string | null
          attributes: Json
          building_id: string
          capacity: number
          close_time: string
          code: string
          department_id: string | null
          features: string[]
          id: string
          is_active: boolean
          name: string
          open_days: number[]
          open_time: string
          qr_secret: string
          systems_count: number
          type: Database["public"]["Enums"]["room_type"]
        }
        Insert: {
          access?: Database["public"]["Enums"]["access_rule"]
          approver_id?: string | null
          attributes?: Json
          building_id: string
          capacity: number
          close_time?: string
          code: string
          department_id?: string | null
          features?: string[]
          id?: string
          is_active?: boolean
          name: string
          open_days?: number[]
          open_time?: string
          qr_secret?: string
          systems_count?: number
          type: Database["public"]["Enums"]["room_type"]
        }
        Update: {
          access?: Database["public"]["Enums"]["access_rule"]
          approver_id?: string | null
          attributes?: Json
          building_id?: string
          capacity?: number
          close_time?: string
          code?: string
          department_id?: string | null
          features?: string[]
          id?: string
          is_active?: boolean
          name?: string
          open_days?: number[]
          open_time?: string
          qr_secret?: string
          systems_count?: number
          type?: Database["public"]["Enums"]["room_type"]
        }
        Relationships: [
          {
            foreignKeyName: "rooms_approver_id_fkey"
            columns: ["approver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rooms_building_id_fkey"
            columns: ["building_id"]
            isOneToOne: false
            referencedRelation: "buildings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rooms_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      analytics_bookings: {
        Args: {
          p_building_code?: string
          p_from: string
          p_room_type?: string
          p_to: string
          p_weekday?: number
        }
        Returns: {
          building_code: string
          ends: string
          ghost: boolean
          headcount: number
          held: boolean
          request_id: string
          requester_kind: Database["public"]["Enums"]["requester_kind"]
          room_code: string
          room_id: string
          room_type: string
          starts: string
          status: Database["public"]["Enums"]["request_status"]
          title: string
          unplaced_reason: string
          used: boolean
        }[]
      }
      analytics_ghost_rate: {
        Args: {
          p_building_code?: string
          p_from: string
          p_group_by: string
          p_room_type?: string
          p_to: string
        }
        Returns: {
          bookings: number
          ghosts: number
          group_key: string
          label: string
          rate_pct: number
        }[]
      }
      analytics_heatmap: {
        Args: { p_building_code?: string; p_from: string; p_room_type?: string; p_to: string }
        Returns: {
          booked: number
          hour: number
          occupancy: number
          room_hours: number
          weekday: number
        }[]
      }
      analytics_hour_slots: {
        Args: { p_building_code?: string; p_from: string; p_room_type?: string; p_to: string }
        Returns: {
          building_code: string
          hour: number
          room_id: string
          slot_start: string
          weekday: number
        }[]
      }
      analytics_idle_building_hours: {
        Args: { p_building_code?: string; p_from: string; p_room_type?: string; p_to: string }
        Returns: {
          building_code: string
          idle_hours: number
          open_hours: number
        }[]
      }
      analytics_open_windows: {
        Args: {
          p_building_code?: string
          p_from: string
          p_room_type?: string
          p_to: string
          p_weekday?: number
        }
        Returns: {
          building_code: string
          closes: string
          day: string
          opens: string
          room_id: string
        }[]
      }
      analytics_rooms: {
        Args: { p_building_code?: string; p_room_type?: string }
        Returns: {
          building_code: string
          close_time: string
          code: string
          is_active: boolean
          name: string
          open_days: number[]
          open_time: string
          room_id: string
          type: Database["public"]["Enums"]["room_type"]
        }[]
      }
      analytics_time_band: { Args: { p_at: string }; Returns: string }
      analytics_time_band_label: { Args: { p_band: string }; Returns: string }
      analytics_underused_rooms: {
        Args: {
          p_building_code?: string
          p_from: string
          p_room_type?: string
          p_threshold_pct: number
          p_to: string
          p_weekday?: number
        }
        Returns: {
          building_code: string
          code: string
          name: string
          occupancy_pct: number
          open_hours: number
          room_id: string
          type: Database["public"]["Enums"]["room_type"]
          used_hours: number
        }[]
      }
      analytics_unmet_demand: {
        Args: {
          p_building_code?: string
          p_from: string
          p_group_by: string
          p_room_type?: string
          p_to: string
        }
        Returns: {
          group_key: string
          label: string
          requests: number
          seats: number
        }[]
      }
      analytics_unmet_requests: {
        Args: { p_building_code?: string; p_from: string; p_room_type?: string; p_to: string }
        Returns: {
          ends: string
          headcount: number
          reason: string
          request_id: string
          room_type: string
          starts: string
          title: string
        }[]
      }
      analytics_utilization: {
        Args: {
          p_building_code?: string
          p_from: string
          p_room_type?: string
          p_to: string
          p_weekday?: number
        }
        Returns: {
          bookings: number
          building_code: string
          code: string
          is_active: boolean
          name: string
          occupancy_pct: number
          open_hours: number
          room_id: string
          type: Database["public"]["Enums"]["room_type"]
          used_hours: number
        }[]
      }
      apply_plan: {
        Args: {
          p_action: string
          p_actor: string
          p_at: string
          p_inserts: Json
          p_moves: Json
        }
        Returns: undefined
      }
      is_admin: { Args: never; Returns: boolean }
      is_valid_transition: {
        Args: {
          f: Database["public"]["Enums"]["request_status"]
          t: Database["public"]["Enums"]["request_status"]
        }
        Returns: boolean
      }
    }
    Enums: {
      access_rule: "open" | "dept_only"
      purpose_kind:
        | "exam"
        | "academic"
        | "department_event"
        | "club_event"
        | "meeting"
        | "student_activity"
      request_status:
        | "waitlisted"
        | "pending"
        | "approved"
        | "checked_in"
        | "completed"
        | "rejected"
        | "expired"
        | "cancelled"
        | "auto_released"
        | "bumped"
      requester_kind: "faculty" | "club" | "department" | "student"
      room_type:
        | "lab"
        | "classroom"
        | "seminar_hall"
        | "meeting_room"
        | "auditorium"
      user_role: "requester" | "approver" | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      access_rule: ["open", "dept_only"],
      purpose_kind: [
        "exam",
        "academic",
        "department_event",
        "club_event",
        "meeting",
        "student_activity",
      ],
      request_status: [
        "waitlisted",
        "pending",
        "approved",
        "checked_in",
        "completed",
        "rejected",
        "expired",
        "cancelled",
        "auto_released",
        "bumped",
      ],
      requester_kind: ["faculty", "club", "department", "student"],
      room_type: [
        "lab",
        "classroom",
        "seminar_hall",
        "meeting_room",
        "auditorium",
      ],
      user_role: ["requester", "approver", "admin"],
    },
  },
} as const
